### ISSUE TITLE
Add strictSSL option to request

### ISSUE THREAD

**Issue by diogonicoleti** [eladnava/cachet-api#4]
I'm using Cachet.io with a wildcard certificade from GoDaddy and when I try to use `cachet-api` this error occurs:
```
Error to check component status: { Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

According to `request` documentation:

> strictSSL - If true, requires SSL certificates be valid. Note: to use your own certificate authority, you need to specify an agent that was created with that CA as an option.

Is possible to add this option to `cachet-api` with value `false`?

**Comment by eladnava** [comment]
Hi @diogonicoleti,
Doing this will compromise the security of this package as an attacker could forge a certificate for a domain and cause this package to trust the certificate blindly.

There is no reason a wildcard SSL certificate would not be supported by Node.js, unless it was improperly configured on your server (i.e. the certificate chain is not in the correct order).

**Comment by eladnava** [comment]
Please consult StackOverflow for resolving this issue as it is out of the scope of this package. 👍

**Comment by diogonicoleti** [comment]
@elednava no problem! Probably my certificate was configured incorrectly. I'll check it. Thanks
