### ISSUE TITLE
Check for required parameters incorrect

### ISSUE THREAD

**Issue by keyndark** [eladnava/cachet-api#6]
Hi. 

If boolen "visible: false" when reportIncident this part of code can`t go forward.

`        // Check for required parameters
        if (!incident.name || !incident.message || !incident.status || !incident.visible) {
            return reject(new Error('Please provide the incident name, message, status, and visibility.'));
        }`

**Comment by eladnava** [comment]
Hi @keyndark,
Nice catch, care to submit a PR with the fix? We simply want to make sure the parameter exists (but `false` is okay, so checking for `undefined` might be good).

**Comment by keyndark** [comment]
#7

**Comment by eladnava** [comment]
Cheers @keyndark, excellent work. Published as `1.0.6`.
