### ISSUE TITLE
Add requests ca option to specify certificates

### ISSUE THREAD

**Issue by MeStrak** [eladnava/cachet-api#9]
Hello there,
We're using Cachet internally, and our internal domain has a self signed certificate. When I use the package (trying to publish a metric to Cachet) I get the following error:

`Error: self signed certificate in certificate chain`

To fix it we need to be able to specify the internally signed cert using the ca option in requests like this:
https://stackoverflow.com/questions/22258093/node-js-using-https-request-with-an-internal-ca

Could this option be added to provide a ca cert to the cachet-api package?

Thanks!

**Comment by eladnava** [comment]
Thanks @MeStrak, merged and published in `1.0.7`. 💯
